title: La Brigata dei Geek Estinti
author: Alessandro Franceschi
email: al@labrigatadeigeekestinti.com
tagline: Geek variegati, curiosi, esperti ed eclettici che parlano di cose. Non per tutti.
description: >-
  Un podcast ad assetto variabile, dove nemmeno l'host sa chi saranno i partecipanti. Potenzialmente, per scelta "editoriale" nessuno o ogni geek che abbia partecipato ad una precedente episodio. A volte ci sono puntate a Microfono Aperto, dove chiunque può entrare.
  Così, senza reti, si parla di argomenti di interesse per geek di ieri e di oggi, dal retrocomputing and platform engineering, dall'intelligenza artificiale allo sviluppo di codice, con divagazioni su tempi più pop, non strettamente informatici.
url: "https://labrigatadeigeekestinti.com" 
baseurl: "/"
logo: "/assets/images/logo.png"
favicon: "/assets/favicons/favicon.ico"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  episodes:
    output: true
    permalink: /ep/:title/
  geek:
    output: true
    permalink: /geek/:title/
    

# Defaults
defaults:
  - scope:
      path: ""
      type: "episodes"
    values:
      layout: "episode"
      author: "default"

# Navigation
nav:
  - title: "Home"
    url: "/"
  - title: "Episodi"
    url: "/episodi/"
  - title: "Geek"
    url: "/geek/"
  - title: "AGE"
    url: "/age/"
  - title: "BGV"
    url: "/bgv/"
  - title: "WTF"
    url: "/wtf/"

social:
  name: La Brigata dei Geek Estinti
  links:
    - https://twitter.com/geekestinti
    - https://www.linkedin.com/company/la-brigata-dei-geek-estinti/
    - https://youtube.com/@labrigatadeigeekestinti
    - https://instagram.com/labrigatadeigeekestinti

webmaster_verifications:
  google: 1234
  bing: 1234